jablue-12/crave

- backend/pom.xml
- backend/src/main/java/com/crave/backend/BackendApplication.java
- backend/src/main/java/com/crave/backend/CraveConfig.java
- backend/src/main/java/com/crave/backend/controller/RestaurantController.java
- backend/src/main/java/com/crave/backend/model/Restaurant.java
- backend/src/main/java/com/crave/backend/repository/RestaurantRepository.java
- backend/src/main/java/com/crave/backend/service/RestaurantService.java
- backend/src/main/resources/application.properties
- backend/src/test/java/com/crave/backend/BackendApplicationTests.java
- backend/src/test/java/com/crave/backend/model/RestaurantTest.java
- Add GET request for retrieving the list of restaurants, as well as retrieving a restaurant by id
- Add POST request for creating a new restaurant
- Add PUT request for updating the existing restaurant
- Add DELETE request for deleting a restaurant
> Dashboards API creation

- backend/src/main/java/com/crave/backend/controller/AccountController.java
- backend/src/main/java/com/crave/backend/controller/CommentController.java
- backend/src/main/java/com/crave/backend/controller/OrderItemController.java
- backend/src/main/java/com/crave/backend/controller/RestaurantItemController.java
- backend/src/main/java/com/crave/backend/controller/UserOrderController.java
> Add CORS to controller

- backend/src/test/java/com/crave/backend/unit/AccountTest.java
- backend/src/test/java/com/crave/backend/unit/RestaurantTest.java
- Update the folder name to be `unit` instead of `model` to keep all the unit tests in the same directory, especially when adding the logic tests for the `Services` class
#57
> Create unit test folder

- backend/src/main/java/com/crave/backend/enums/OrderStatus.java
- backend/src/main/java/com/crave/backend/model/UserOrder.java
- backend/src/test/java/com/crave/backend/unit/AccountTest.java
- backend/src/test/java/com/crave/backend/unit/CommentTest.java
- backend/src/test/java/com/crave/backend/unit/OrderItemTest.java
- backend/src/test/java/com/crave/backend/unit/RestaurantItemTest.java
- backend/src/test/java/com/crave/backend/unit/UserOrderTest.java
- Create tests for the missing domain objects
- Include enum file for user order status
#59
> Unit tests for domain objects

- frontend/.gitignore
- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/dashboard/Map.jsx
- frontend/src/components/dashboard/RestaurantsDashboard.jsx
- frontend/src/components/menu/Menu.jsx
- frontend/src/components/nav/Header.jsx
- frontend/src/tests/components/cart/Cart.test.jsx
- frontend/src/tests/components/loader/Loader.test.jsx
- frontend/src/tests/components/rating/Rating.test.jsx
Fix the UI bug when the backend is not running
#29
#49
> Add Google Map intergration

- backend/pom.xml
- backend/src/test/java/com/crave/backend/unit/RestaurantServiceTest.java
- backend/src/test/resources/application.properties
- Test all methods in the `RestaurantService` by using the mock library.
- Setup the h2 database for testing the repositories when custom sql statements are added.
#66
> Unit tests for RestaurantService

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/dashboard/Map.jsx
- Need to setup .env file locally under the `frontend` directory
- Use `npm install dotenv` if environment variable does not work
> Use env varaible for MAP API

- .gitignore
- Dockerfile-README.md
- backend/Dockerfile
- backend/pom.xml
- backend/src/main/resources/application.yml
- docker-compose.yml
- frontend/.dockerignore
- frontend/Dockerfile
- Create Dockerfile for frontend
- Create Dockerfile for backend
- Create docker-compose.yml file to execute multiple containers which are frontend, backend, and postgres. Note that you need to create a .env file in the root directory (crave folder) for the POSTGRES environment variables.
- Create a Docker-README.md that contains a list of commands for docker-compose
- Update pom.yml to use java version 17. This should not conflict with any code from the backend
#46
> Docker setup

- backend/src/main/java/com/crave/backend/config/CraveConfig.java
- backend/src/main/resources/application.yml
- Update the application.yml file to make the data persist instead of dropping the schema whenever the application is stopped.
#93
> Make database persist

- backend/src/main/java/com/crave/backend/config/JwtAuthenticationFilter.java
- backend/src/main/java/com/crave/backend/config/SecurityConfig.java
- backend/src/main/java/com/crave/backend/controller/AuthenticationController.java
- backend/src/main/java/com/crave/backend/enums/TokenType.java
- backend/src/main/java/com/crave/backend/model/Account.java
- backend/src/main/java/com/crave/backend/model/Token.java
- backend/src/main/java/com/crave/backend/model/auth/AuthenticationResponse.java
- backend/src/main/java/com/crave/backend/repository/TokenRepository.java
- backend/src/main/java/com/crave/backend/service/AccountService.java
- backend/src/main/java/com/crave/backend/service/AuthenticationService.java
- backend/src/main/java/com/crave/backend/service/LogoutService.java
- backend/src/test/java/com/crave/backend/unit/AccountRepositoryTest.java
- backend/src/test/java/com/crave/backend/unit/AccountTest.java
- Implement the logout logic.
- The path for the logout POST request is _**auth/logout**_ . Ensure that you provide the **_BEARER TOKEN_** on the request so that the backend can revoke the valid token.
- Add status messages on registration and login authentication.
#84
> Logout Implementation

- backend/Dockerfile
- Hotfix on the backend Dockerfile
> Hotfix on backend Dockerfile

- backend/src/main/java/com/crave/backend/controller/AccountController.java
- backend/src/main/java/com/crave/backend/controller/AuthenticationController.java
- backend/src/main/java/com/crave/backend/controller/UserOrderController.java
- backend/src/main/java/com/crave/backend/dto/UserDTO.java
- backend/src/main/java/com/crave/backend/service/AccountService.java
- backend/src/main/java/com/crave/backend/service/AuthenticationService.java
- Use spring security to get the user details.
- Use UserDTO to avoid exposing sensitive data such as user password.
- Modify UserDTO to expose user role.
#100
> Fix retrieving authenticated user

- frontend/src/components/features/dashboard/core/Comments.jsx
- frontend/src/components/features/dashboard/core/Dish.jsx
- Adjust the structure of the endpoint on the Comments component for retrieving the list of comments.
> Hotfix on Comments component

- backend/src/main/java/com/crave/backend/config/CraveConfig.java
- backend/src/main/java/com/crave/backend/controller/DishController.java
- backend/src/main/java/com/crave/backend/model/Dish.java
- backend/src/test/java/com/crave/backend/unit/CommentTest.java
- backend/src/test/java/com/crave/backend/unit/DishTest.java
- backend/src/test/resources/application.properties
- frontend/src/common/constants.js
- frontend/src/components/common/FeedbackMessage.jsx
- frontend/src/components/features/dashboard/core/Ingredient.jsx
- frontend/src/components/features/nav/Header.jsx
- frontend/src/components/pages/DishCreation.jsx
- frontend/src/index.js
- Create a page for creating dishes that contains validations (minimal).
- Create a feedback msg component to display a message to the user once they create a dish.
- Adjust test db to use H2 instead of Postgres to ensure that hibernate generates sql statements compatible with H2 during testing.
#116
> Dish Creation Page

- frontend/package-lock.json
- frontend/package.json
> Change dependencies

- frontend/cypress.config.js
- frontend/cypress/e2e/auth.cy.js
- frontend/cypress/e2e/dashboard.cy.js
- frontend/cypress/fixtures/dishes.json
- frontend/cypress/support/commands.js
- frontend/cypress/support/component-index.html
- frontend/cypress/support/component.js
- frontend/cypress/support/e2e.js
- frontend/cypress/utils/generateString.js
- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/features/auth/AuthForm.jsx
- frontend/src/components/features/auth/Register.jsx
- frontend/src/components/features/dashboard/core/Dish.jsx
- frontend/src/components/features/dashboard/core/DishCard.jsx
- frontend/src/components/features/nav/Header.jsx
- frontend/src/contexts/AuthContext.js
> Add Cypress tests for dashboard, dish details, and authentication

- backend/src/main/java/com/crave/backend/model/Account.java
- backend/src/main/java/com/crave/backend/model/Ingredient.java
- backend/src/main/java/com/crave/backend/model/OrderItem.java
- backend/src/main/java/com/crave/backend/model/Restaurant.java
- backend/src/main/java/com/crave/backend/model/RestaurantItem.java
- backend/src/main/java/com/crave/backend/model/Token.java
- backend/src/main/java/com/crave/backend/model/UserOrder.java
- backend/src/test/java/com/crave/backend/unit/AccountTest.java
- backend/src/test/java/com/crave/backend/unit/AuthenticationRequestTest.java
- backend/src/test/java/com/crave/backend/unit/AuthenticationResponseTest.java
- backend/src/test/java/com/crave/backend/unit/CommentDTOTest.java
- backend/src/test/java/com/crave/backend/unit/CommentRepositoryTest.java
- backend/src/test/java/com/crave/backend/unit/DishRepositoryTest.java
- backend/src/test/java/com/crave/backend/unit/OrderItemTest.java
- backend/src/test/java/com/crave/backend/unit/RegisterRequestTest.java
- backend/src/test/java/com/crave/backend/unit/RestaurantItemTest.java
- backend/src/test/java/com/crave/backend/unit/TokenRepositoryTest.java
- backend/src/test/java/com/crave/backend/unit/TokenTest.java
- backend/src/test/java/com/crave/backend/unit/UserDTOTest.java
- backend/src/test/java/com/crave/backend/unit/UserOrderTest.java
- Make unit tests for models to be 100% code coverage.
- Create unit tests for DTOs.
- Create unit tests for the missing repositories that have custom queries.
#59 #80
> Unit tests for Model, DTOs and Repository

- backend/src/test/java/com/crave/backend/unit/service/AccountServiceTest.java
- backend/src/test/java/com/crave/backend/unit/service/AuthenticationServiceTest.java
- backend/src/test/java/com/crave/backend/unit/service/CommentServiceTest.java
- backend/src/test/java/com/crave/backend/unit/service/DishServiceTest.java
- backend/src/test/java/com/crave/backend/unit/service/IngredientServiceTest.java
- backend/src/test/java/com/crave/backend/unit/service/LogoutServiceTest.java
- backend/src/test/java/com/crave/backend/unit/service/OrderItemServiceTest.java
- backend/src/test/java/com/crave/backend/unit/service/RestaurantItemServiceTest.java
- backend/src/test/java/com/crave/backend/unit/service/UserOrderServiceTest.java
> add service tests

- backend/src/test/java/com/crave/backend/integration/IngredientControllerTest.java
- backend/src/test/java/com/crave/backend/integration/IngredientServiceTest.java
> Integration Tests

- backend/src/test/java/com/crave/backend/unit/dto/CommentDTOTest.java
- backend/src/test/java/com/crave/backend/unit/dto/UserDTOTest.java
- backend/src/test/java/com/crave/backend/unit/model/AccountTest.java
- backend/src/test/java/com/crave/backend/unit/model/AuthenticationRequestTest.java
- backend/src/test/java/com/crave/backend/unit/model/AuthenticationResponseTest.java
- backend/src/test/java/com/crave/backend/unit/model/CommentTest.java
- backend/src/test/java/com/crave/backend/unit/model/DishTest.java
- backend/src/test/java/com/crave/backend/unit/model/IngredientTest.java
- backend/src/test/java/com/crave/backend/unit/model/OrderItemTest.java
- backend/src/test/java/com/crave/backend/unit/model/RegisterRequestTest.java
- backend/src/test/java/com/crave/backend/unit/model/RestaurantItemTest.java
- backend/src/test/java/com/crave/backend/unit/model/RestaurantTest.java
- backend/src/test/java/com/crave/backend/unit/model/TokenTest.java
- backend/src/test/java/com/crave/backend/unit/model/UserOrderTest.java
- backend/src/test/java/com/crave/backend/unit/repository/AccountRepositoryTest.java
- backend/src/test/java/com/crave/backend/unit/repository/CommentRepositoryTest.java
- backend/src/test/java/com/crave/backend/unit/repository/DishRepositoryTest.java
- backend/src/test/java/com/crave/backend/unit/repository/TokenRepositoryTest.java
- backend/src/test/java/com/crave/backend/unit/service/RestaurantServiceTest.java
> Move unit test files in their specified folder

- README.md
- backend/src/main/java/com/crave/backend/config/SecurityConfig.java
- Update README to include links for deployments
> Add CORS for deployed frontend (Hotfix)

- backend/src/test/java/com/crave/backend/integration/AuthenticationServiceTest.java
- backend/src/test/java/com/crave/backend/integration/CommentServiceTest.java
- backend/src/test/java/com/crave/backend/integration/DishServiceTest.java
- backend/src/test/java/com/crave/backend/integration/IngredientServiceTest.java
> Create service integration tests

- .github/workflows/sonarcloud-scanner.yml
- backend/pom.xml
> Integrate SonarCloud to CI

- backend/src/main/java/com/crave/backend/controller/DishController.java
- backend/src/main/java/com/crave/backend/model/Dish.java
- backend/src/main/java/com/crave/backend/service/DishService.java
- backend/src/main/java/com/crave/backend/utils/ImageUtils.java
- backend/src/test/java/com/crave/backend/integration/DishServiceTest.java
- backend/src/test/java/com/crave/backend/unit/model/CommentTest.java
- backend/src/test/java/com/crave/backend/unit/model/DishTest.java
- backend/src/test/java/com/crave/backend/unit/repository/CommentRepositoryTest.java
- backend/src/test/java/com/crave/backend/unit/repository/DishRepositoryTest.java
- backend/src/test/java/com/crave/backend/unit/service/DishServiceTest.java
- backend/src/test/java/com/crave/backend/unit/utils/ImageUtilsTest.java
- frontend/src/App.jsx
- frontend/src/common/api.js
- frontend/src/components/features/dashboard/core/Dish.jsx
- frontend/src/components/features/dashboard/core/DishCard.jsx
- frontend/src/components/pages/DishCreation.jsx
- frontend/src/contexts/DishCreationContext.js
- Update Dish model properties and adjust the unit tests related to the change.
- Add an endpoint to upload a dish image on a specific dish.
- Add an endpoint to retrieve the uploaded image.
- Create a utility to compress and decompress image files.
- Refactor DishCreation page to use context/provider.
#147
> Create dish image endpoints

- backend/src/main/java/com/crave/backend/controller/AuthenticationController.java
- backend/src/main/java/com/crave/backend/model/auth/UpdateRequest.java
- backend/src/main/java/com/crave/backend/service/AuthenticationService.java
- Path to do a PUT request for updating the profile is: `http://localhost:8080/auth/user`
- Note: you need to update the TOKEN in the local storage when you update the profile successfully.
JSON request body:
```
{
"firstName": "updated firstname",
"lastName": "updated lastname",
"email": "new-email@gmail.com",
"oldPassword": "oldpass",
"newPassword": "newpass"
}
```
JSON response body:
```
{
"token": "token here",
"statusMessage": "message response here"
}
```
#152
> Inlcude update profile endpoint

- frontend/src/components/features/auth/LoginForm.jsx
- frontend/src/components/features/auth/RegisterForm.jsx
- frontend/src/components/features/dashboard/core/DishForm.jsx
- frontend/src/components/features/dashboard/core/IngredientForm.jsx
- frontend/src/components/features/nav/Header.jsx
- frontend/src/contexts/AuthContext.js
- Include email regex for validity.
- Update Dish Tag to be selectable.
- Create new design for login and register form that includes feedback  messages from the backend, as well providing valid/invalid messages.
> Update Account components

- backend/src/main/java/com/crave/backend/controller/UserOrderController.java
- backend/src/main/java/com/crave/backend/model/OrderItem.java
- backend/src/main/java/com/crave/backend/model/UserOrder.java
- backend/src/main/java/com/crave/backend/service/UserOrderService.java
- backend/src/test/java/com/crave/backend/unit/model/UserOrderTest.java
- backend/src/test/java/com/crave/backend/unit/service/UserOrderServiceTest.java
- frontend/src/common/constants.js
- frontend/src/components/common/Submit.jsx
- frontend/src/components/features/auth/LoginForm.jsx
- frontend/src/components/features/auth/RegisterForm.jsx
- frontend/src/components/features/cart/ShoppingCart.jsx
- frontend/src/components/features/dashboard/core/DishForm.jsx
- frontend/src/components/features/dashboard/core/IngredientForm.jsx
- frontend/src/components/features/nav/Header.jsx
- frontend/src/components/features/user/Profile.jsx
- frontend/src/contexts/AuthContext.js
- frontend/src/contexts/CartContext.js
- frontend/src/contexts/OrderContext.js
Fix additional UI bugs
- [BUG] Fix link error when clicking the user icon.
- [BUG] Fix error on profile page with duplicate keys for displaying the orders.
- [BUG] email validation for regex with myumanitoba.ca
- [BUG] Use the logout endpoint from the backend to revoke the user's token.
- [BUG] Adjust userOrder endpoint to display total price.
- [UI-FIX] Create a reusable button component which is used by login,register,dish,ingredient,pay-order forms.
- [UI-FIX] Include dish image on shopping cart.
- Include feedback message when placing an order.
#145 
#30 
#29
> Refactor Frontend

- frontend/src/common/api.js
- frontend/src/components/features/auth/ProfileForm.jsx
- frontend/src/components/features/user/Profile.jsx
- Use the endpoint for updating the profile information.
#86
> Update profile (Frontend)

- frontend/src/common/constants.js
- frontend/src/components/features/cart/ShoppingCart.jsx
- frontend/src/components/features/dashboard/core/Dish.jsx
- Fix ChatGPT bug endpoint.
- Update submit button when placing an order.
> Sprint 4 Bug Fix on chatgpt
